### ISSUE TITLE
Unnecessary error message

### ISSUE THREAD

**Issue by assylias** [AgoraDesk-LocalMonero/website-bug-tracker#1]
With an account that has 0 XMR, create a Buy ad.

Then amend the ad to change the margin (for example) and you get an error:

> Form error  
> Minimum transaction amount cannot be lower than your current balance. Try lowering minimum amount or depositing funds to your LocalMonero wallet

This should probably only be applied to sell orders.

Workaround: delete the ad and create a new one.

**Comment by LocalMonero** [comment]
Thanks for pointing it out. We're on it.

**Comment by applebaum** [comment]
Fixed.
