### ISSUE TITLE
sell/buy mix up

### ISSUE THREAD

**Issue by qral** [AgoraDesk-LocalMonero/website-bug-tracker#3]
Hey guys,
I'm kind of confused by the ads on the site. I'm trying Czech Republic and there is only one listing, but it sometimes appears as the guy is Seller (selling XMR) and sometimes he's buyer (buying XMR). 

I figured out he's buyer, but it should be fixed. Maybe even the wording should be changed - I checked the Germany and it's simple **Sell/Buy Monero online in Germany** not **Sell Monero with cash in Czech Republic**. 
How can I "SELL Monero WITH CASH"? 

Edit: When I'm trying to search for Buy/Sell ads now there is NONE in Czech Rep. But on landing page I see one again. 

URL: https://localmonero.co/user/cryptopath 
<img width="1336" alt="screen shot 2017-10-09 at 20 12 19" src="https://user-images.githubusercontent.com/74139/31352213-3547765c-ad2e-11e7-9b8a-3c169d726376.png">

URL: https://localmonero.co/
<img width="1585" alt="screen shot 2017-10-09 at 20 13 32" src="https://user-images.githubusercontent.com/74139/31352257-5eb3d4cc-ad2e-11e7-8ce2-88fee3e69488.png">

https://localmonero.co/ad?type=ONLINE_SELL&currencyCode=CZK&countryCode=CZ&paymentMethodCode=&amount=
<img width="831" alt="screen shot 2017-10-09 at 20 17 32" src="https://user-images.githubusercontent.com/74139/31352431-0b217228-ad2f-11e7-8551-baf8393460a7.png">

https://localmonero.co/ad?type=ONLINE_BUY&currencyCode=CZK&countryCode=CZ&paymentMethodCode=&amount=
<img width="784" alt="screen shot 2017-10-09 at 20 18 02" src="https://user-images.githubusercontent.com/74139/31352434-0fbc8930-ad2f-11e7-836c-1441178c4319.png">

**Comment by LocalMonero** [comment]
He's buying XMR for cash. In the search box you chose "All online offers" as your payment method. Local ads will not be listed under that choice. If you want to buy or sell for cash you need to select "Cash (locally)" as your payment method. If you do that, you'll see that cryptopath's ad does show up.
