### ISSUE TITLE
Allow easy export of transaction history

### ISSUE THREAD

**Issue by assylias** [AgoraDesk-LocalMonero/website-bug-tracker#6]
At the moment, the only way to retrieve transaction history out of the site is to copy/paste some html which is not convenient.

An export function that generates a csv file would be a great addition.

**Comment by applebaum** [comment]
Great idea! I'll get on that, expect it in the nearest time.

**Comment by applebaum** [comment]
Done.

**Comment by assylias** [comment]
That was quick, thanks.
